session_name: dots
windows:
  - window_name: git
    layout: tiled
    panes:
      - lazygit
  - window_name: nvim
    layout: tiled
    panes:
      - nvim .
  - window_name: shell
    layout: tiled
    panes:
      - echo "Hi, I'm Paul!"
