version: '3'

tasks:
  rebuild:
    cmds:
      - sudo nixos-rebuild switch --flake . --impure

  show_ip:
    cmds:
      - hostname -I

  service:xremap:restart:
    cmds:
      - systemctl restart xremap.service
