version: '3'
tasks:
  hm:
    cmds:
      - docker build -f hm.Dockerfile . -t dot_box
      - docker container rm -f dot_box || true
      - |
        docker run \
          -it \
          --name dot_box \
          -v ../:/root/dots \
          -v dotbox-nix-store:/nix/store/ \
          -v dotbox-local:/root/.local/ \
          -v dotbox-cache:/root/.cache/ \
          -e XDG_CONFIG_HOME="/root/dots/xdg-config/" \
        dot_box
  up:
    cmds:
      - docker container rm -f dot_box || true
      - |
        docker run \
          -it \
          --name dot_box \
          -v ../:/root/dots \
          -v dotbox-nix-store:/nix/store/ \
          -v dotbox-local:/root/.local/ \
          -v dotbox-cache:/root/.cache/ \
          -e XDG_CONFIG_HOME="/root/dots/xdg-config/" \
        nixos/nix:latest \
        nix \
          --extra-experimental-features nix-command \
          --extra-experimental-features flakes \
        develop /root/dots -c bash
