#!/usr/bin/env bash

cat << EOF >> README.md
See [docs](./docs) directory
EOF


mkdir docs || true


cat << EOF >> docs/BRANCHING_STRATEGY.md
[Trunk based development](https://trunkbaseddevelopment.com/)
EOF

cat << EOF >> docs/CONTRIBUTING.md
Add your docs here
EOF

cat << EOF >> docs/DEPLOYMENTS.md
Add your docs here
EOF

cat << EOF >> docs/DEV_SETUP.md
# DEV_SETUP

### (If not already installed) Install nix and dev env

- https://nixos.org/download/
- https://direnv.net/

\`\`\`
// NOTE: you must be in a git repo with the flake file tracked for this to work! Make sure to run git init...

direnv allow

direnv reload
\`\`\`
EOF

cat << EOF >> docs/LEARNING_RESOURCES.md
[12 factor apps](https://12factor.net/)
EOF

cat << EOF >> docs/PATTERNS.md
Add your docs here
EOF

cat << EOF >> docs/RUNBOOKS.md
Add your docs here
EOF

cat << EOF >> docs/TODOS.md
# TODOS
Add your TODOS here! Here are some thoughts to get your started

## Scripts
- CICD wrappers (quality check, build, deploy)

## Golang server
- Set up tests, linting, formatting, coverage
- Set up archunit
- Set up SQLC
- Set up structured logging / SLOG

## Typescript app
- Set up tests, linting, formatting, coverage
- Set up archunit

## OpenAPI
- Manage openapi directly
- Generate gin server from definition
- Generate typescript client from definition

## Testing
- Add newman tests
- Add playwright tests

## MISC
- Static analysis / sonar scanning
- Add IAC modules (e.g. TF, HELM, etc)
EOF
