session_name: ${TUX_SESSION_NAME}
start_directory: ${TUX_START_DIR}
windows:
  - window_name: git
    layout: tiled
    panes:
      - lazygit
  - window_name: nvim
    layout: tiled
    panes:
      - nvim .
  - window_name: tests
    layout: tiled
    panes:
      - null
  - window_name: server
    layout: tiled
    panes:
      - null
  - window_name: repl
    layout: tiled
    panes:
      - null
  - window_name: misc
    layout: tiled
    panes:
      - null
