services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    profiles: [deps, all]
    ports:
      - "8082:8080"
    volumes:
      - ../openapi/openapi-generated.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
      # API_URL: ""
