services:
  deps_postgres:
    container_name: postgres
    profiles: [deps, all]
    ports:
      - 5432:5432
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
